// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ReservationCore.Models
{
    public partial class HotelReservationContext : DbContext
    {
        public HotelReservationContext()
        {
        }

        public HotelReservationContext(DbContextOptions<HotelReservationContext> options)
            : base(options)
        {
        }

        public virtual DbSet<MealPlans> MealPlans { get; set; }
        public virtual DbSet<MealPlansPerSeason> MealPlansPerSeason { get; set; }
        public virtual DbSet<Reservations> Reservations { get; set; }
        public virtual DbSet<RoomType> RoomType { get; set; }
        public virtual DbSet<RoomsPerSeason> RoomsPerSeason { get; set; }
        public virtual DbSet<Season> Season { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MealPlans>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();
            });

            modelBuilder.Entity<MealPlansPerSeason>(entity =>
            {
                entity.HasKey(e => new { e.MealPlanId, e.SeasonId });

                entity.HasOne(d => d.MealPlan)
                    .WithMany(p => p.MealPlansPerSeason)
                    .HasForeignKey(d => d.MealPlanId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_meal_plans_per_season_meal_plans");

                entity.HasOne(d => d.Season)
                    .WithMany(p => p.MealPlansPerSeason)
                    .HasForeignKey(d => d.SeasonId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_meal_plans_per_season_season");
            });

            modelBuilder.Entity<Reservations>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.HasOne(d => d.MealPlan)
                    .WithMany(p => p.Reservations)
                    .HasForeignKey(d => d.MealPlanId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_reservations_reservations");

                entity.HasOne(d => d.RoomTypeNavigation)
                    .WithMany(p => p.Reservations)
                    .HasForeignKey(d => d.RoomType)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_reservations_room_type1");

                entity.HasOne(d => d.Season)
                    .WithMany(p => p.Reservations)
                    .HasForeignKey(d => d.SeasonId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_reservations_season");
            });

            modelBuilder.Entity<RoomsPerSeason>(entity =>
            {
                entity.HasKey(e => new { e.SeasonId, e.RoomType })
                    .HasName("PK_rooms_per_season_1");

                entity.HasOne(d => d.RoomTypeNavigation)
                    .WithMany(p => p.RoomsPerSeason)
                    .HasForeignKey(d => d.RoomType)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_rooms_per_season_room_type");

                entity.HasOne(d => d.Season)
                    .WithMany(p => p.RoomsPerSeason)
                    .HasForeignKey(d => d.SeasonId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_rooms_per_season_season");
            });

            modelBuilder.Entity<Season>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}