// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ReservationCore.Models
{
    [Table("meal_plans")]
    public partial class MealPlans
    {
        public MealPlans()
        {
            MealPlansPerSeason = new HashSet<MealPlansPerSeason>();
            Reservations = new HashSet<Reservations>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("meal_plan")]
        [StringLength(50)]
        public string MealPlan { get; set; }

        [InverseProperty("MealPlan")]
        public virtual ICollection<MealPlansPerSeason> MealPlansPerSeason { get; set; }
        [InverseProperty("MealPlan")]
        public virtual ICollection<Reservations> Reservations { get; set; }
    }
}