// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ReservationCore.Models
{
    public partial class MealPlan
    {
        public MealPlan()
        {
            Reservation = new HashSet<Reservation>();
            SeasonsMealPrice = new HashSet<SeasonsMealPrice>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [InverseProperty("Meal")]
        public virtual ICollection<Reservation> Reservation { get; set; }
        [InverseProperty("MealPlan")]
        public virtual ICollection<SeasonsMealPrice> SeasonsMealPrice { get; set; }
    }
}