// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ReservationCore.Models
{
    [Table("reservations")]
    public partial class Reservations
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("name")]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        [Required]
        [Column("email")]
        [StringLength(50)]
        public string Email { get; set; }
        [Column("adults")]
        public int Adults { get; set; }
        [Column("childs")]
        public int? Childs { get; set; }
        [Column("meal_plan_id")]
        public int MealPlanId { get; set; }
        [Column("season_id")]
        public int SeasonId { get; set; }
        [Required]
        [Column("room_type")]
        [StringLength(50)]
        public string RoomType { get; set; }
        [Column("check_in", TypeName = "date")]
        public DateTime CheckIn { get; set; }
        [Column("check_out", TypeName = "date")]
        public DateTime CheckOut { get; set; }

        [ForeignKey("MealPlanId")]
        [InverseProperty("Reservations")]
        public virtual MealPlans MealPlan { get; set; }
        [ForeignKey("RoomType")]
        [InverseProperty("Reservations")]
        public virtual RoomType RoomTypeNavigation { get; set; }
        [ForeignKey("SeasonId")]
        [InverseProperty("Reservations")]
        public virtual Season Season { get; set; }
    }
}