// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ReservationCore.Models
{
    [Table("room_type")]
    public partial class RoomType
    {
        public RoomType()
        {
            Reservations = new HashSet<Reservations>();
            RoomsPerSeason = new HashSet<RoomsPerSeason>();
        }

        [Key]
        [Column("room_type")]
        [StringLength(50)]
        public string RoomType1 { get; set; }

        [InverseProperty("RoomTypeNavigation")]
        public virtual ICollection<Reservations> Reservations { get; set; }
        [InverseProperty("RoomTypeNavigation")]
        public virtual ICollection<RoomsPerSeason> RoomsPerSeason { get; set; }
    }
}