// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ReservationCore.Models
{
    [Table("rooms_per_season")]
    public partial class RoomsPerSeason
    {
        [Key]
        [Column("season_id")]
        public int SeasonId { get; set; }
        [Key]
        [Column("room_type")]
        [StringLength(50)]
        public string RoomType { get; set; }
        [Column("price")]
        public double Price { get; set; }

        [ForeignKey("RoomType")]
        [InverseProperty("RoomsPerSeason")]
        public virtual RoomType RoomTypeNavigation { get; set; }
        [ForeignKey("SeasonId")]
        [InverseProperty("RoomsPerSeason")]
        public virtual Season Season { get; set; }
    }
}