// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ReservationCore.Models
{
    public partial class SeaonsRoomPrice
    {
        [Key]
        public int RoomId { get; set; }
        [Key]
        public int SeasonId { get; set; }
        [Column(TypeName = "decimal(6, 2)")]
        public decimal? Price { get; set; }

        [ForeignKey("RoomId")]
        [InverseProperty("SeaonsRoomPrice")]
        public virtual RoomType Room { get; set; }
        [ForeignKey("SeasonId")]
        [InverseProperty("SeaonsRoomPrice")]
        public virtual Season Season { get; set; }
    }
}