// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ReservationCore.Models
{
    [Table("season")]
    public partial class Season
    {
        public Season()
        {
            MealPlansPerSeason = new HashSet<MealPlansPerSeason>();
            Reservations = new HashSet<Reservations>();
            RoomsPerSeason = new HashSet<RoomsPerSeason>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("from", TypeName = "date")]
        public DateTime? From { get; set; }
        [Column("to", TypeName = "date")]
        public DateTime? To { get; set; }

        [InverseProperty("Season")]
        public virtual ICollection<MealPlansPerSeason> MealPlansPerSeason { get; set; }
        [InverseProperty("Season")]
        public virtual ICollection<Reservations> Reservations { get; set; }
        [InverseProperty("Season")]
        public virtual ICollection<RoomsPerSeason> RoomsPerSeason { get; set; }
    }
}