// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ReservationCore.Models
{
    public partial class SeasonsMealPrice
    {
        [Key]
        public int MealPlanId { get; set; }
        [Key]
        public int SeasonId { get; set; }
        [Column(TypeName = "decimal(6, 2)")]
        public decimal Price { get; set; }

        [ForeignKey("MealPlanId")]
        [InverseProperty("SeasonsMealPrice")]
        public virtual MealPlan MealPlan { get; set; }
        [ForeignKey("SeasonId")]
        [InverseProperty("SeasonsMealPrice")]
        public virtual Season Season { get; set; }
    }
}