// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ReservationCore.Models
{
    public partial class Season
    {
        public Season()
        {
            Reservation = new HashSet<Reservation>();
            SeaonsRoomPrice = new HashSet<SeaonsRoomPrice>();
            SeasonsMealPrice = new HashSet<SeasonsMealPrice>();
        }

        [Key]
        public int Id { get; set; }
        [Column(TypeName = "date")]
        public DateTime StartDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime EndDate { get; set; }

        [InverseProperty("Season")]
        public virtual ICollection<Reservation> Reservation { get; set; }
        [InverseProperty("Season")]
        public virtual ICollection<SeaonsRoomPrice> SeaonsRoomPrice { get; set; }
        [InverseProperty("Season")]
        public virtual ICollection<SeasonsMealPrice> SeasonsMealPrice { get; set; }
    }
}